modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "sdmshop"
version = "${version}"
displayName = "SDMShop"
authors = ""
description = '''

'''
#logoFile = ""

[[dependencies.sdmshop]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sdmshop]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sdmshop]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.sdmshop]]
modId = "sdm_ui_lib"
mandatory = true
versionRange = "[1.20.1-1.8.3,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.sdmshop]]
modId = "ftblibrary"
mandatory = true
versionRange = "[2001.2.9,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.sdmshop]]
modId = "sdmeconomy"
mandatory = true
versionRange = "[2.2.0,)"
ordering = "AFTER"
side = "BOTH"
